# Siddur Sefard - Sefardic/Mediterranean Prayer Book
# Data fetched from Sefaria and enhanced with traditional liturgical content

PRAYERS_DATA = {
    "Upon Arising": {
        "en": "Morning Blessings\n\nModeh Ani - The gratitude prayer recited immediately upon awakening, before washing hands. A foundational blessing expressing thanks for the return of the soul to the body after sleep.",
        "he": "ברכות ההשכמה\n\nמודה אני קודם כל לפניך מלך חי וקיים שהחזרת בי נשמתי בחמלה רבה אמונתך.",
        "ar": "الصلوات الصباحية\n\nمودة ني - صلاة الامتنان المتواصلة فور الاستيقاظ، قبل غسل اليدين.",
        "ru": "Утренние благословения\n\nМодэ ани - молитва благодарности, читаемая сразу после пробуждения, до мытья рук."
    },
    "Weekday Shacharit": {
        "en": "Morning Prayer Service (Weekday Shacharit)\n\nMODEH ANI\nModeh ani lefanecha melech chai vekayam, shehechezarta bi nishmati bechemla, raba emunatecha.\nI offer thanks before You, living and eternal King, for You have mercifully restored my soul within me; Your faithfulness is great.\n\nNETILAT YADAYIM (Hand Washing)\nBaruch Atah Adonai, Eloheinu Melech haolam, asher kideshanu bemitzvotav vetzivanu al netilat yadayim.\nBlessed are You, Lord our God, King of the universe, Who has sanctified us with His commandments and commanded us concerning the washing of the hands.\n\nBIRKAT HATORAH (Torah Blessings)\nBaruch Atah Adonai, Eloheinu Melech haolam, asher bachar banu mikol haamim venatan lanu et torato.\nBlessed are You, Lord our God, King of the universe, Who has chosen us from all peoples and given us His Torah.\n\nSHEMA YISRAEL\nShema Yisrael, Adonai Eloheinu, Adonai Echad.\nHear O Israel, the Lord is our God, the Lord is One.\n\nVeahavta et Adonai Elohecha bechol levavcha uvechol nafshecha uvechol meodecha. Vehayu hadevarim haeleh asher anochi metzavecha hayom al levavecha.\nAnd you shall love the Lord your God with all your heart, with all your soul, and with all your might. These words which I command you this day shall be upon your heart.\n\nAMIDAH (Standing Prayer - 19 Blessings)\nBaruch Atah Adonai, Eloheinu Velohei avoteinu, Elohei Avraham, Elohei Yitzchak, vElohei Yaakov...\nBlessed are You, Lord our God and God of our ancestors, God of Abraham, God of Isaac, and God of Jacob... (the Amidah consists of 19 blessings recited silently while standing)\n\nALEINU\nAleinu leshabeach laAdon hakol, latet gedulah leyotzer bereshit...\nIt is our duty to praise the Master of all, to exalt the Creator of the universe...",
        "he": "תפילת השחרית לימות החול\n\nשירות התפילה העיקרי של הבוקר הכולל ברכות ההשכמה, הכנת הלב, קריאת שמע ישראל וברכותיו, ותפילת העמידה. מרכז בחיים הרוחניים של הישראלים.",
        "ar": "دعاء الصباح في أيام الأسبوع\n\nخدمة الصلاة اليومية الرئيسية في الصباح تشمل البركات الصباحية وتحضير القلب وقراءة شمع إسرائيل وبركاته.",
        "ru": "Утренняя молитва в будни\n\nОсновная ежедневная служба молитвы, включающая утренние благословения, подготовку сердца, чтение Шемы Израиль и его благословений."
    },
    "Weekday Mincha": {
        "en": "Afternoon Prayer Service (Weekday Mincha)\n\nASHREI (Psalm 145)\nAshrei yoshvei veitecha, od yehaleluca selah. Ashrei haam shekachah lo, ashrei haam she-Adonai Elohav.\nHappy are those who dwell in Your house; they will praise You forever. Happy is the people for whom this is so; happy is the people whose God is the Lord.\n\nTehila leDavid - A Song of Praise by David:\nAromimcha Elohai hamelech, va-avaracha shimcha leolam va-ed...\nI will extol You, my God the King, and bless Your Name for ever and ever...\n\nCHAZARAT HASHATZ (Reader's Repetition) omitted in Mincha.\n\nAMIDAH (Mincha - 19 Blessings, recited silently)\nBaruch Atah Adonai, Eloheinu Velohei avoteinu...\nBlessed are You, Lord our God and God of our ancestors...\n\nKEDUSHAH (during repetition)\nNekadesh et shimcha baolam, keshem shemakdishim oto bishmei marom...\nWe sanctify Your Name in the world, as it is sanctified in the highest heavens...\n\nALEINU\nAleinu leshabeach laAdon hakol, latet gedulah leyotzer bereshit, shelo asanu kegoyei haaratzot...\nIt is our duty to praise the Master of all, to exalt the Creator of the universe, Who has not made us like the nations of the lands...",
        "he": "תפילת המנחה לימות החול\n\nשירות התפילה של אחר הצהריים המתורגמת לאחר חצות הלכתית ולפני שקיעה. כוללת קריאות כתובי הקודש ותפילות הכנה.",
        "ar": "دعاء العصر في أيام الأسبوع\n\nخدمة الصلاة بعد الظهر التي تتواصل بعد الظهيرة الشرعية وقبل الغروب. تشمل القراءات الكتابية والصلوات التحضيرية.",
        "ru": "Молитва послеполудня в будни\n\nСлужба молитвы полудня, которая традиционно читается после халарического полудня и до заката."
    },
    "Weekday Maariv": {
        "en": "Evening Prayer Service (Weekday Maariv)\n\nBARCHU (Call to Prayer)\nBarechu et Adonai hamevorah!\nBless the Lord Who is blessed!\nBaruch Adonai hamevorah leolam vaed!\nBlessed is the Lord Who is blessed for all eternity!\n\nMA'ARIV ARAVIM (Evening Blessing)\nBaruch Atah Adonai, Eloheinu Melech haolam, asher bidvaro maariv aravim, bechochma poteach shearim...\nBlessed are You, Lord our God, King of the universe, Who by His word brings on the evenings, with wisdom opens the gates of heaven...\n\nSHEMA YISRAEL\nShema Yisrael, Adonai Eloheinu, Adonai Echad.\nHear O Israel, the Lord is our God, the Lord is One.\n\nAMIDAH (Evening - 19 Blessings, recited silently)\nBaruch Atah Adonai, Eloheinu Velohei avoteinu...\nBlessed are You, Lord our God and God of our ancestors...\n\nALEINU\nAleinu leshabeach laAdon hakol...\nIt is our duty to praise the Master of all...\n\nKADDISH YATOM (Mourner's Kaddish)\nYitgadal veyitkadash shmeh raba. Beolma di vra chiruteh...\nMagnified and sanctified is His great Name, in the world which He created according to His will...",
        "he": "תפילת הערבית לימות החול\n\nשירות התפילה של הערב המתורגמת לאחר צאת הכוכבים. מתחילה בקריאת שמע וברכותיה, ואחריה תפילת העמידה.",
        "ar": "دعاء المساء في أيام الأسبوع\n\nخدمة الصلاة المسائية المتواصلة بعد ظهور النجوم. تبدأ بقراءة شمع وبركاته.",
        "ru": "Вечерняя молитва в будни\n\nСлужба молитвы вечера, читаемая после появления звезд. Начинается с чтения Шемы и его благословений."
    },
    "Bedtime Shema": {
        "en": "Master of the universe! I hereby forgive anyone who has angered me, or sinned against me, either physically or financially, against my honor or anything that is mine, whether accidentally or intentionally, inadvertently or deliberately, by speech or by deed, in this incarnation or in any other any Israelite [is forgiven], may no man be punished on my account. May it be Your will, Adonoy, my God and God of my fathers, that I shall sin no more nor repeat my sins, neither shall I again anger You nor do what is wrong in Your eyes. Blessed are You, Adonoy, our God, King of the Universe, Who causes the fetters of sleep to fall upon my eyes, and slumber upon my eyelids. Blessed are You, Lord, Who illuminates the whole world with His glory.",
        "he": "רִבּוֹנוֹ שֶׁל־עוֹלָם הֲרֵינִי מוֹחֵל לְכָל־מִי שֶׁהִכְעִיס וְהִקְנִיט אוֹתִי אוֹ שֶׁחָטָא כְּנֶגְדִי בֵּין בְּגוּפִי בֵּין בְּמֶמוֹנִי בֵין בִּכְבוֹדִי בֵין בְכָל אֲשֶׁר לִי בֵין בְּאוֹנֶס בֵּין בְּרָצוֹן בֵּין בְּשׁוֹגֵג בֵּין בְּמֵזִיד בֵין בְּדִבּוּר בֵּין בְּמַעֲשֶׂה בֵּין בְּגִלְגוּל זֶה בֵּין בְּגִלְגּוּל אַחֵר לְכָל־בַּר יִשְׂרָאֵל וְלֹא יֵעָנֵשׁ שׁוּם אָדָם בְסִבָּתִי. יְהִי רָצוֹן מִלְּפָנֶֽיךָ יְהֹוָה אֱלֹהַי וֵאלֹהֵי אֲבוֹתַי שֶׁלֹּא אֶחְטֶא עוֹד וְלֹא אֶחֱזוֹר בָּהֶם וְלֹא אָשׁוּב עוֹד לְהַכְעִיסֶךָ וְלֹא אֶעֱשֶׂה הָרַע בְּעֵינֶֽיךָ. בָּרוּךְ אַתָּה יְהֹוָה אֱלֹהֵֽינוּ מֶֽלֶךְ הָעוֹלָם הַמַּפִּיל חֶבְלֵי שֵׁנָה עַל עֵינָי וּתְנוּמָה עַל עַפְעַפָּי. בָּרוּךְ אַתָּה יְהֹוָה הַמֵּאִיר לָעוֹלָם כֻּלּוֹ בִּכְבוֹדוֹ.",
        "ar": "يا سيد العالم، أغفر لكل من أغاظني أو أخطأ تجاهي شاه م الجسد أوالمال أو الشرف أو أي شيء آخر بقصد أو بغير قصد. قد يكون مغفوراً له. يا إلهي، اجعل مشيئتك أنني لن أخطئ مجدداً. بارك أنت يا إلهي ملك العالم الذي يسبب الخمول.",
        "ru": "Владыка вселенной! Я прощаю каждого, кто рассердил или согрешил передо мной, будь то в отношении тела или имущества, чести или чего-либо еще мне принадлежащего, случайно или намеренно. Да будет воля Твоя, Боже мой, чтобы я не грешил более. Благословен Ты, Господи, Боже наш, Царь вселенной, Кто посылает сон на мои очи."
    },
    "Kiddush Levanah": {
        "en": "Blessing the New Moon (Kiddush Levanah)\n\nBlessed are You, Lord, our God, King of the Universe, who with His utterance created the heavens, and with the breath of His mouth, all their host. Law and season did He give them, that they not deviate from their set function. They are glad and rejoice to do the will of their Creator — the Worker of truth whose work is true. The moon He directed to renew itself — a crown of glory to those who are borne from the womb, who are destined to be renewed just like it, and to glorify their Creator for the name of His glorious kingdom. Blessed are You, Lord, Renewer of the months.",
        "he": "בָּרוּךְ אַתָּה יְהֹוָה אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר בְּמַאֲמָרוֹ בָּרָא שְׁחָקִים, וּבְרוּחַ פִּיו כָּל צְבָאָם, חֹק וּזְמַן נָתַן לָהֶם שֶׁלּא יְשַׁנּוּ אֶת תַּפְקִידָם, שָׂשִׂים וּשְׂמֵחִים לַעֲשׂוֹת רְצוֹן קוֹנָם. וְלַלְּבָנָה אָמַר שֶׁתִּתְחַדֵּשׁ, עֲטֶרֶת תִּפְאֶרֶת לַעֲמוּסֵי בָטֶן שֶׁהֵם עֲתִידִים לְהִתְחַדֵּשׁ כְּמוֹתָהּ. בָּרוּךְ אַתָּה יְהֹוָה מְחַדֵּשׁ חֳדָשִׁים.",
        "ar": "بارك أنت يا إلهنا ملك العالم الذي بكلمته خلق السموات وبنفس فمه كل جنودها. أعطاهم ناموساً وميقاتاً حتى لا يحرفوا عن وظائفهم. فرحون ومسرورون لتنفيذ مشيئة خالقهم. والقمر أمره أن يتجدد، إكليل مجد لحاملي الأجنة الذين هم مقدر لهم التجدد مثله.",
        "ru": "Благословен Ты, Господи, Боже наш, Царь вселенной, Который словом Своим создал небеса и дыханием уст Своих - все их воинства. Закон и время дал Он им, чтобы они не уклонялись от своего предназначения. Луне велел Он обновляться - венец славы тем, кто рожден из утробы, кто предназначен обновляться подобно ей. Благословен Ты, Господи, обновляющий месяцы."
    },
    "Kiddush": {
        "en": "Kiddush - Sanctification of Shabbat\n\nFRIDAY NIGHT KIDDUSH\n\nVAYECHULU (Genesis 2:1-3)\nVayechulu hashamayim veha'aretz vechol tzeva'am. Vayechal Elohim bayom hashevi'i melachto asher asah, vayishbot bayom hashevi'i mikol melachto asher asah. Vayevarech Elohim et yom hashevi'i vayekadesh oto, ki vo shavat mikol melachto asher bara Elohim la'asot.\nThe heavens and earth were completed with all their host. On the seventh day God completed His work that He had done, and He rested on the seventh day from all His work. God blessed the seventh day and sanctified it, for on it He rested from all His work that God created to make.\n\nKIDDUSH BLESSING\nBaruch Atah Adonai, Eloheinu Melech haolam, borei peri hagafen.\nBlessed are You, Lord our God, King of the universe, Who creates the fruit of the vine.\n\nBaruch Atah Adonai, Eloheinu Melech haolam, asher kideshanu bemitzvotav veratzah vanu, veShabbat kodsho beahavah uvratzon hinchilanu, zikaron lema'aseh vereshit. Ki hu yom techilah lemikraei kodesh, zecher litziat Mitzrayim. Ki vanu vacharta veotanu kidashta mikol haamim. VeShabbat kodshecha beahavah uvratzon hinchaltanu. Baruch Atah Adonai, mekadesh haShabbat.\nBlessed are You, Lord our God, King of the universe, Who has sanctified us with His commandments and has taken pleasure in us, and in love and favor gave us His holy Shabbat as an inheritance, a remembrance of the act of Creation. For it is the beginning of the holy convocations, a remembrance of the Exodus from Egypt. For You chose us and sanctified us from all peoples, and the holy Shabbat, in love and favor, You gave us as our heritage. Blessed are You, Lord, Who sanctifies the Shabbat.",
        "he": "בָּרוּךְ אַתָּה יְהֹוָה אֱלֹהֵֽינוּ מֶֽלֶךְ הָעוֹלָם בּוֹרֵא פְּרִי הַגָּֽפֶן: וַיְכֻלּוּ הַשָּׁמַיִם וְהָאָרֶץ וְכָל צְבָאָם וַיִּשְׁבֹּת בַּיּוֹם הַשְּׁבִיעִי.",
        "ar": "بارك أنت يا إلهنا ملك العالم خالق ثمرة الكرم. هذا الدعاء يقدس يوم الراحة أو العيد، مما يؤسس انفصالاً بين العادي والمقدس.",
        "ru": "Благословен Ты, Господи, Боже наш, Царь вселенной, создающий плод виноградной лозы. Это благословение освящает день отдыха или праздника."
    },
    "Havdalah": {
        "en": "Havdalah - Separation Ceremony (End of Shabbat)\n\nHINEH EL YESHUATI (Isaiah 12:2-3)\nHineh El yeshuati evtach velo efchad, ki ozi vezimrat Yah Adonai vayehi li lishuah. Ushavtem mayim besasson mima'aynei hayeshuah.\nBehold, God is my salvation; I will trust and not be afraid, for God the Lord is my strength and song, and He has become my salvation. You shall draw water with joy from the springs of salvation.\n\nLEHAVDALAH - THE FOUR BLESSINGS\n\n1. WINE - Baruch Atah Adonai, Eloheinu Melech haolam, borei peri hagafen.\nBlessed are You, Lord our God, King of the universe, Who creates the fruit of the vine.\n\n2. SPICES (Besamim) - Baruch Atah Adonai, Eloheinu Melech haolam, borei minei vesamim.\nBlessed are You, Lord our God, King of the universe, Who creates various spices.\n\n3. FIRE (Ner) - Baruch Atah Adonai, Eloheinu Melech haolam, borei meorei haesh.\nBlessed are You, Lord our God, King of the universe, Who creates the lights of fire.\n\n4. HAVDALAH - Baruch Atah Adonai, Eloheinu Melech haolam, hamavdil bein kodesh lechol, bein or lechoshech, bein Yisrael laamim, bein yom hashevi'i lesheshet yemei hama'aseh. Baruch Atah Adonai, hamavdil bein kodesh lechol.\nBlessed are You, Lord our God, King of the universe, Who distinguishes between sacred and secular, between light and darkness, between Israel and the nations, between the seventh day and the six days of work. Blessed are You, Lord, Who distinguishes between sacred and secular.\n\nELIYAHU HANAVI (traditional song)\nEliyahu hanavi, Eliyahu hatishbi, Eliyahu hagiladi. Bimhera veyameinu yavo eleinu, im Mashiach ben David.\nElijah the prophet, Elijah the Tishbite, Elijah the Gileadite. May he come to us speedily, in our days, with the Messiah son of David.",
        "he": "הַבְדָּלָה\n\nהַבְדָּלָה (הָפְרָדָה) נֶאֱמֶרֶת לְאַחַר צְאַת הַכּוֹכָבִים בְּמוֹצְאֵי שַׁבָּת. הִיא מְסָיְּמֶת אֶת הַשַּׁבָּת וּמַשְׁמַרְתֶּת הַפְּרָדָה בֵּין הַיּוֹם הַקָּדוֹשׁ לִיּוֹם הַחוּל הָרְגִיל. כּוֹלֶלֶת בְּרָכוֹת עַל יַיִן וּלְבוֹנוֹת וְאֵשׁ.",
        "ar": "الهافدالاه (الفصل)\n\nتُتلى الهافدالاه بعد ظهور النجوم في مساء السبت. وهي تحدد الختام لـ يوم السبت والفصل بين اليوم المقدس واليوم العادي العادي.",
        "ru": "Хавдала (Разделение)\n\nХавдала читается после появления звезд в субботний вечер. Она знаменует окончание Шабата и разделение между святым днем и обычным буднем."
    },
    "Shabbat Shacharit": {
        "en": "Shabbat Morning Prayer Service (Shacharit)\n\nPESUKEI DEZIMRA - Verses of Praise\nBeginning with Baruch sheamar and including Ashrei and Hallel-Psalms, culminating in Az Yashir (Song of the Sea).\n\nAshrei yoshvei veitecha, od yehaleluca selah...\nHappy are those who dwell in Your house; they will praise You forever...\n\nSHABBAT SHACHARIT AMIDAH (7 Blessings)\nThe Shabbat Amidah has 7 blessings instead of the weekday 19. The middle blessing is unique to Shabbat:\n\nYismach Moshe bematnat chelko, ki eved ne'eman karata lo. Klil tiferet berosho natata, beomdo lefanecha al Har Sinai. Shtei luchot avanim horid beyado, vechatuv bahem shmirat Shabbat...\nMoses rejoiced in the gift of his portion, for You called him a faithful servant. A glorious crown did You place upon his head when he stood before You on Mount Sinai. Two stone tablets he brought down in his hands, and written on them is the observance of the Shabbat...\n\nKEDUSHAT HAYOM (Shabbat Sanctification)\nYismechu vmalchutcha shomrei Shabbat vekorei oneg, am mekadshei shevi'i, kulam yisbu veyitangu mituvecha...\nThose who observe the Shabbat and call it a delight will rejoice in Your kingship. A people who sanctify the seventh day, all shall be satisfied and take pleasure in Your goodness...\n\nTORAH READING\nOn Shabbat morning, the weekly Torah portion (parasha) is read from the Torah scroll along with a Haftarah portion from the Prophets.\n\nMUSAF AMIDAH\nTikunnu Shabbat ratzita korbanotehah... You desired the Shabbat offerings...",
        "he": "תפילת השחרית של שבת\n\nגרסת שבת המורחבת של התפילות הבוקריות כוללת תהילים נוספים, פיוטים, ותפילת העמידה המיוחדת של שבת. השירות שם דגש על קדושת היום.",
        "ar": "صلاة الصباح ليوم السبت\n\nنسخة السبت الموسعة من صلوات الصباح تشمل مزامير إضافية وقصائد ليتورجية والعمدة الخاصة بيوم السبت.",
        "ru": "Утренняя молитва в Шабат\n\nРасширенная версия шабатских утренних молитв включает дополнительные псалмы, литургические стихи и специальную молитву Амиду для Шабата."
    },
    "Shabbat Mincha": {
        "en": "Shabbat Afternoon Prayer Service\n\nThe afternoon prayer service for Shabbat includes a special third meal (Seudah Shlishit), Torah discussion, and the contemplative Shabbat Amidah. This service often features spiritual discussions and joyful singing as the holy day continues.",
        "he": "תפילת המנחה של שבת\n\nשירות התפילה של אחר הצהריים לשבת כולל ארוחה שלישית מיוחדת, דיון בתורה, ותפילת העמידה של שבת.",
        "ar": "صلاة العصر ليوم السبت\n\nخدمة الصلاة بعد الظهر ليوم السبت تشمل وجبة ثالثة خاصة ونقاش التوراة والعمدة التأملية.",
        "ru": "Молитва послеполудня в Шабат\n\nСлужба молитвы полудня в Шабат включает специальный третий прием пищи, обсуждение Торы и созерцательную молитву Амиду Шабата."
    },
    "Holiday Prayers": {
        "en": "Holiday Prayer Services (Yom Tov)\n\nHALLEL - Psalms of Praise (recited on most holidays)\nHalleluyah! Praise servants of the Lord, praise the Name of the Lord. Blessed be the Name of the Lord from now and forever...\n\nHodu laAdonai ki tov, ki leolam chasdo. Yomar na Yisrael, ki leolam chasdo...\nGive thanks to the Lord for He is good, for His kindness endures forever. Let Israel say: for His kindness endures forever...\n\nMINHA SHEL YOM TOV - Afternoon Holiday Service\nThe afternoon holiday service follows the regular Mincha structure with additions specific to each holiday.\n\nMUSSAF - Additional Service\nOn Rosh Hashanah, Yom Kippur, Sukkot, Pesach, and Shavuot, a Mussaf (additional) Amidah is recited:\n\nRESHIT YAMIM - ROSH HASHANAH ADDITIONS\nZochreinu lechaim, melech chafeitz bachaim, vechotvenu besefer hachaim lemanchacha Elohim chaim.\nRemember us for life, O King Who desires life, and inscribe us in the Book of Life — for Your sake, O living God.\n\nYOM KIPPUR - KOL NIDRE\nKol nidre veasare, ushvuei, vacharamei, vekonamei, vekinuyei, vechinuyei, veshma'ot — dindarna udishta'bana, udacharimna, vedeasarnan al nafshatana...\nAll vows, prohibitions, oaths, consecrations, pledges, that we have vowed, sworn, devoted, or bound ourselves to — from this Yom Kippur to next Yom Kippur... we hereby declare all these to be null and void.\n\nSUKKOT - HALLEL (complete Hallel recited all 8 days)\nPESACH - HALLEL (partial Hallel on Chol HaMoed and last days)\nSHAVUOT - Commemorating the giving of the Torah at Sinai",
        "he": "שירות תפילה לחגים\n\nתפילות לחגים יהודיים כוללות הוספות ליטורגיות מיוחדות לתפילות היומיות הרגילות. לכל חג יש נושאים תיאולוגיים ייחודיים.",
        "ar": "خدمات الصلاة للعطل\n\nتتضمن الصلوات للأعياد اليهودية إضافات ليتורجية خاصة إلى الصلوات اليومية العادية.",
        "ru": "Молитвенные службы для праздников\n\nМолитвы для еврейских праздников включают специальные литургические добавления к обычным ежедневным молитвам."
    }
}
