sonar.organization=akivayevdayev-debug
sonar.projectKey=akivayevdayev-debug_Shelah_app

sonar.sources=.
sonar.exclusions=graphify-out/**,static/vendor/**,**/__pycache__/**,**/*.min.js,tests/**

sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
