"""Tests for scripts/generate_database_doc.py.

The generator's contract is what makes docs/DATABASE.md trustworthy: the doc is
rendered purely from the introspected schema, and ``--check`` must fail exactly
when the committed doc and the live schema disagree -- while ignoring the one
machine-written header line (run date + project ref) that changes on every run.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import pytest

SCRIPT_PATH = Path(__file__).resolve().parent.parent / "scripts" / "generate_database_doc.py"


def _load_script():
    spec = importlib.util.spec_from_file_location("generate_database_doc", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gdd = _load_script()

SNAPSHOT = {
    "tables": [
        {
            "table_name": "study_bookmarks",
            "columns": [
                {"name": "id", "type": "uuid", "nullable": False, "default": "gen_random_uuid()"},
                {"name": "ref", "type": "text", "nullable": True, "default": None},
            ],
            "indexes": [{"name": "study_bookmarks_pkey", "def": "CREATE UNIQUE INDEX ..."}],
            "rls_enabled": True,
            "rls_forced": False,
            "policies": [{"name": "owner_only", "cmd": "ALL", "roles": "{authenticated}",
                          "using": "(user_id = auth.uid())", "with_check": None}],
        },
        {"table_name": "answer_feedback", "columns": [], "rls_enabled": False},
    ]
}


class TestSmallHelpers:
    @pytest.mark.parametrize("url, ref", [
        ("https://abcdxyz.supabase.co", "abcdxyz"),
        ("https://abcdxyz.supabase.co/rest/v1", "abcdxyz"),
        ("localhost", "localhost"),
        ("", "unknown"),
    ])
    def test_project_ref_is_the_first_host_label(self, url, ref):
        assert gdd._project_ref(url) == ref

    def test_default_is_code_formatted_or_an_em_dash(self):
        assert gdd._fmt_default("now()") == "`now()`"
        assert gdd._fmt_default(None) == "—"
        assert gdd._fmt_default(0) == "`0`"


class TestRenderTable:
    def test_renders_columns_indexes_rls_flags_and_policies(self):
        md = gdd._render_table(SNAPSHOT["tables"][0])

        assert "### `study_bookmarks`" in md
        assert "| `id` | `uuid` | NOT NULL | `gen_random_uuid()` |" in md
        assert "| `ref` | `text` | YES | — |" in md
        assert "- `study_bookmarks_pkey`: `CREATE UNIQUE INDEX ...`" in md
        assert "**RLS enabled**: True · **RLS forced**: False" in md
        assert "- `owner_only` (ALL, roles: {authenticated}) — USING: `(user_id = auth.uid())` · WITH CHECK: `—`" in md

    def test_tables_without_indexes_or_policies_omit_those_sections(self):
        md = gdd._render_table(SNAPSHOT["tables"][1])

        assert "**Indexes**" not in md
        assert "**Policies**" not in md
        assert "**RLS enabled**: False · **RLS forced**: False" in md

    def test_missing_name_renders_a_visible_placeholder(self):
        assert "### `?`" in gdd._render_table({})


class TestRenderDoc:
    def render(self, snapshot=SNAPSHOT, on="2026-01-02", ref="abcdxyz"):
        return gdd.render_doc(snapshot, project_ref=ref, generated_on=on)

    def test_tables_are_sorted_by_name_so_the_diff_is_stable(self):
        doc = self.render()
        assert doc.index("### `answer_feedback`") < doc.index("### `study_bookmarks`")

    def test_header_records_the_run_date_and_project(self):
        assert ("> _Generated by `scripts/generate_database_doc.py` on 2026-01-02 "
                "against project `abcdxyz`.") in self.render()

    def test_document_ends_with_exactly_one_newline(self):
        doc = self.render()
        assert doc.endswith("\n") and not doc.endswith("\n\n")

    def test_empty_snapshot_still_renders_the_static_sections(self):
        doc = self.render({"tables": None})
        assert "## Tables" in doc and "## Data Retention" in doc

    def test_strip_header_makes_runs_on_different_days_and_projects_comparable(self):
        a = self.render(on="2026-01-02", ref="proj-a")
        b = self.render(on="2027-05-06", ref="proj-b")

        assert a != b
        assert gdd._strip_header(a) == gdd._strip_header(b)

    def test_strip_header_does_not_hide_a_real_schema_change(self):
        changed = {"tables": [{**SNAPSHOT["tables"][1], "rls_enabled": True}]}
        before = self.render({"tables": [SNAPSHOT["tables"][1]]})
        after = self.render(changed)

        assert gdd._strip_header(before) != gdd._strip_header(after)


class TestResolveSupabaseConfig:
    @pytest.fixture(autouse=True)
    def _no_dotenv(self, monkeypatch):
        monkeypatch.setattr(gdd, "load_dotenv", lambda: None)

    def test_returns_stripped_credentials(self, monkeypatch):
        monkeypatch.setenv("SUPABASE_URL", " https://p.supabase.co ")
        monkeypatch.setenv("SUPABASE_SECRET_KEY", " sk ")
        assert gdd.resolve_supabase_config() == {"url": "https://p.supabase.co", "secret_key": "sk"}

    @pytest.mark.parametrize("missing", ["SUPABASE_URL", "SUPABASE_SECRET_KEY"])
    def test_missing_credentials_exit_2_with_a_message_on_stderr(self, monkeypatch, capsys, missing):
        monkeypatch.setenv("SUPABASE_URL", "https://p.supabase.co")
        monkeypatch.setenv("SUPABASE_SECRET_KEY", "sk")
        monkeypatch.delenv(missing)

        with pytest.raises(SystemExit) as exc:
            gdd.resolve_supabase_config()

        assert exc.value.code == 2
        assert "cannot introspect the live schema" in capsys.readouterr().err


class TestFetchSchemaSnapshot:
    CONFIG = {"url": "https://p.supabase.co", "secret_key": "sk"}

    def _client(self, monkeypatch, *, data=None, error=None):
        seen = {}

        class _Rpc:
            def execute(self):
                if error:
                    raise error
                return SimpleNamespace(data=data)

        class _Client:
            def rpc(self, name, params):
                seen["rpc"] = (name, params)
                return _Rpc()

        def create_client(url, key):
            seen["create"] = (url, key)
            return _Client()

        monkeypatch.setitem(sys.modules, "supabase", SimpleNamespace(create_client=create_client))
        return seen

    def test_returns_the_snapshot_and_uses_the_service_role_key(self, monkeypatch):
        seen = self._client(monkeypatch, data={"tables": [1]})

        assert gdd.fetch_schema_snapshot(self.CONFIG) == {"tables": [1]}
        assert seen["create"] == ("https://p.supabase.co", "sk")
        assert seen["rpc"] == ("get_schema_snapshot", {})

    def test_list_wrapped_scalar_rpc_result_is_unwrapped(self, monkeypatch):
        self._client(monkeypatch, data=[{"tables": [2]}])
        assert gdd.fetch_schema_snapshot(self.CONFIG) == {"tables": [2]}

    @pytest.mark.parametrize("data", [[], None, {}])
    def test_empty_results_become_an_empty_table_list(self, monkeypatch, data):
        self._client(monkeypatch, data=data)
        assert gdd.fetch_schema_snapshot(self.CONFIG) == {"tables": []}

    def test_rpc_failure_exits_2_and_names_the_prerequisite_sql(self, monkeypatch, capsys):
        self._client(monkeypatch, error=RuntimeError("function does not exist"))

        with pytest.raises(SystemExit) as exc:
            gdd.fetch_schema_snapshot(self.CONFIG)

        assert exc.value.code == 2
        err = capsys.readouterr().err
        assert "introspect_schema.sql" in err
        assert "function does not exist" in err


class TestMain:
    @pytest.fixture
    def wired(self, monkeypatch, tmp_path):
        doc = tmp_path / "docs" / "DATABASE.md"
        doc.parent.mkdir()
        monkeypatch.setattr(gdd, "DOC_PATH", doc)
        monkeypatch.setattr(gdd, "resolve_supabase_config",
                            lambda: {"url": "https://abcdxyz.supabase.co", "secret_key": "sk"})
        monkeypatch.setattr(gdd, "fetch_schema_snapshot", lambda config: SNAPSHOT)
        return doc

    def run(self, monkeypatch, *args):
        monkeypatch.setattr(sys, "argv", ["generate_database_doc", *args])
        return gdd.main()

    def test_default_run_writes_the_rendered_doc(self, wired, monkeypatch, capsys):
        assert self.run(monkeypatch) == 0

        text = wired.read_text(encoding="utf-8")
        assert "### `study_bookmarks`" in text
        assert "against project `abcdxyz`" in text
        assert f"wrote {wired}" in capsys.readouterr().out

    def test_check_passes_when_only_the_header_date_differs(self, wired, monkeypatch, capsys):
        wired.write_text(
            gdd.render_doc(SNAPSHOT, project_ref="other-project", generated_on="1999-01-01"),
            encoding="utf-8")

        assert self.run(monkeypatch, "--check") == 0
        assert "matches the live schema" in capsys.readouterr().out

    def test_check_fails_when_the_committed_doc_is_stale(self, wired, monkeypatch, capsys):
        stale = {"tables": [SNAPSHOT["tables"][1]]}
        wired.write_text(
            gdd.render_doc(stale, project_ref="abcdxyz", generated_on="2026-01-01"),
            encoding="utf-8")

        assert self.run(monkeypatch, "--check") == 1
        assert "does not match the live schema" in capsys.readouterr().err

    def test_check_fails_when_the_doc_does_not_exist_and_writes_nothing(self, wired, monkeypatch, capsys):
        assert self.run(monkeypatch, "--check") == 1
        assert "does not exist yet" in capsys.readouterr().err
        assert not wired.exists()

    def test_check_never_modifies_the_committed_file(self, wired, monkeypatch):
        wired.write_text("hand edited", encoding="utf-8")
        assert self.run(monkeypatch, "--check") == 1
        assert wired.read_text(encoding="utf-8") == "hand edited"


def test_script_entry_point_exits_with_main_return_code(monkeypatch, capsys):
    import runpy

    monkeypatch.setattr(sys, "argv", ["generate_database_doc", "--check"])
    monkeypatch.delenv("SUPABASE_URL", raising=False)
    with patch("dotenv.load_dotenv"), pytest.raises(SystemExit) as exc:
        runpy.run_path(str(SCRIPT_PATH), run_name="__main__")
    assert exc.value.code == 2
