#!/usr/bin/env python3
"""Regenerate docs/DATABASE.md from the live Supabase schema (plan.md §23.2.3).

Why this exists: docs/DATABASE.md was hand-written prose that drifted from
the real schema in almost every particular -- wrong tenant key, tables that
don't exist, tables that do exist but aren't documented -- and that drift
already caused a silent production bug (a consent-record write rejected by
PostgREST because the code was written against the doc's wrong column name;
see plan.md §23.1). Generating the doc from the schema itself is what stops
that class of bug from recurring; hand-correcting the prose once only fixes
today.

Requires scripts/sql/introspect_schema.sql to have been applied to the
target Supabase project first (this script only reads; it does not apply
migrations itself), plus SUPABASE_URL / SUPABASE_SECRET_KEY -- same
resolution as scripts/recompute_ai_usage_log_cost.py.

Usage:
    python scripts/generate_database_doc.py            # write docs/DATABASE.md
    python scripts/generate_database_doc.py --check     # exit 1 if the committed
                                                         # file doesn't match live schema

Run manually or via the same scheduled workflow as §21.2.2's RLS check
(both need live credentials and a deployed target) -- not a per-PR gate.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parent.parent
DOC_PATH = REPO_ROOT / "docs" / "DATABASE.md"

# Matches the machine-written header line so --check can compare bodies
# without every run showing a diff purely from the embedded run date
# ("no timestamps in the body, so the diff is meaningful" -- plan.md
# §23.2.3 -- reconciled with the same section's "carry a machine-written
# header" requirement by excluding just this one line from the comparison).
_HEADER_RE = re.compile(
    r"^> _Generated by `scripts/generate_database_doc\.py` on .*? "
    r"against project `.*?`\. Do not hand-edit this file — see plan\.md §23\.2\.3\._$",
    re.MULTILINE,
)
_HEADER_PLACEHOLDER = "> _Generated by `scripts/generate_database_doc.py`._"


def resolve_supabase_config() -> dict[str, str]:
    load_dotenv()
    url = (os.environ.get("SUPABASE_URL") or "").strip()
    secret_key = (os.environ.get("SUPABASE_SECRET_KEY") or "").strip()
    if not url or not secret_key:
        print(
            "generate_database_doc: SUPABASE_URL / SUPABASE_SECRET_KEY not set -- "
            "cannot introspect the live schema. Set both (e.g. in .env) and retry.",
            file=sys.stderr,
        )
        sys.exit(2)
    return {"url": url, "secret_key": secret_key}


def _project_ref(url: str) -> str:
    host = urlparse(url).hostname or url
    return host.split(".")[0] if host else "unknown"


def fetch_schema_snapshot(config: dict[str, str]) -> dict:
    from supabase import create_client  # local import: only needed when this script actually runs

    client = create_client(config["url"], config["secret_key"])
    try:
        result = client.rpc("get_schema_snapshot", {}).execute()
    except Exception as e:  # noqa: BLE001 - surfaced to the operator, not swallowed
        print(
            "generate_database_doc: get_schema_snapshot() RPC call failed -- has "
            "scripts/sql/introspect_schema.sql been applied to this project's SQL "
            f"editor yet? Underlying error: {e}",
            file=sys.stderr,
        )
        sys.exit(2)

    data = result.data
    if isinstance(data, list):  # some client versions wrap scalar RPC returns in a list
        data = data[0] if data else {}
    return data or {"tables": []}


def _fmt_default(value) -> str:
    return f"`{value}`" if value is not None else "—"


def _render_table(table: dict) -> str:
    name = table.get("table_name", "?")
    lines = [f"### `{name}`", ""]

    columns = table.get("columns") or []
    lines.append("| Column | Type | Nullable | Default |")
    lines.append("|---|---|---|---|")
    for col in columns:
        nullable = "YES" if col.get("nullable") else "NOT NULL"
        lines.append(
            f"| `{col.get('name')}` | `{col.get('type')}` | {nullable} | "
            f"{_fmt_default(col.get('default'))} |"
        )
    lines.append("")

    indexes = table.get("indexes") or []
    if indexes:
        lines.append("**Indexes**:")
        for idx in indexes:
            lines.append(f"- `{idx.get('name')}`: `{idx.get('def')}`")
        lines.append("")

    lines.append(
        f"**RLS enabled**: {bool(table.get('rls_enabled'))} · "
        f"**RLS forced**: {bool(table.get('rls_forced'))}"
    )
    lines.append("")

    policies = table.get("policies") or []
    if policies:
        lines.append("**Policies**:")
        for pol in policies:
            using = pol.get("using") or "—"
            check = pol.get("with_check") or "—"
            lines.append(
                f"- `{pol.get('name')}` ({pol.get('cmd')}, roles: {pol.get('roles')}) "
                f"— USING: `{using}` · WITH CHECK: `{check}`"
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def render_doc(snapshot: dict, *, project_ref: str, generated_on: str) -> str:
    tables = sorted(snapshot.get("tables") or [], key=lambda t: t.get("table_name", ""))

    header = (
        f"> _Generated by `scripts/generate_database_doc.py` on {generated_on} "
        f"against project `{project_ref}`. Do not hand-edit this file — see plan.md §23.2.3._"
    )

    parts = [
        "# Sh'elah — Database Schema Reference",
        "",
        header,
        "",
        "This document describes the Supabase (Postgres) `public`-schema tables used by "
        "Sh'elah, introspected directly from the live project. The application "
        "authenticates users via **Clerk** JWTs and stores the Clerk user ID (`user_id`) "
        "as the tenant key on every user-scoped table below — there is no `clerk_id` "
        "column anywhere in this schema (plan.md §23.1 has the history of why the prior "
        "hand-written version of this doc said otherwise).",
        "",
        "> **Secret-key access only**: the backend always uses `SUPABASE_SECRET_KEY`, "
        "which bypasses RLS. The policies listed per-table below are defense-in-depth — "
        "see plan.md §21 for the open question of whether `auth.uid()` actually resolves "
        "a Clerk JWT in this project at all — and support direct Supabase-dashboard "
        "access.",
        "",
        "---",
        "",
        "## Tables",
        "",
    ]
    parts.extend(_render_table(table) for table in tables)
    parts.extend([
        "## Migrations",
        "",
        "There is no `supabase/` CLI migration directory in this repo (a CLI-migration "
        "workflow adoption was considered and deliberately deferred — plan.md §23.2.3). "
        "Schema changes are hand-pasted `.sql` files, run once in the Supabase SQL "
        "editor: base tables/functions live in `scripts/sql/`, additive `ALTER`s live in "
        "`scripts/migrate_*.sql`. There is no migration-tracking table, ordering "
        "convention, or rollback SQL — this generated doc plus each file's own header "
        "comment (provenance, dependencies) is the closest thing to one.",
        "",
        "---",
        "",
        "## Data Retention",
        "",
        "Enforced by the `retention_enforce` cron (`backend/routes_privacy.py`, "
        "scheduled via `vercel.json`) against `ask_history` and `ai_usage_log` — see "
        "`docs/PRIVACY_OPERATIONS.md` for the full policy.",
        "",
    ])
    return "\n".join(parts).rstrip() + "\n"


def _strip_header(text: str) -> str:
    return _HEADER_RE.sub(_HEADER_PLACEHOLDER, text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Regenerate in memory and diff against the committed file; exit 1 on any "
             "difference (ignoring the header's run date/project ref). Does not write.",
    )
    args = parser.parse_args()

    config = resolve_supabase_config()
    snapshot = fetch_schema_snapshot(config)

    import datetime
    generated_on = datetime.date.today().isoformat()
    rendered = render_doc(snapshot, project_ref=_project_ref(config["url"]), generated_on=generated_on)

    if args.check:
        if not DOC_PATH.exists():
            print(f"generate_database_doc --check: {DOC_PATH} does not exist yet.", file=sys.stderr)
            return 1
        committed = DOC_PATH.read_text(encoding="utf-8")
        if _strip_header(committed) != _strip_header(rendered):
            print(
                "generate_database_doc --check: docs/DATABASE.md does not match the live "
                "schema. Run `python scripts/generate_database_doc.py` and commit the "
                "result.",
                file=sys.stderr,
            )
            return 1
        print("generate_database_doc --check: docs/DATABASE.md matches the live schema.")
        return 0

    DOC_PATH.write_text(rendered, encoding="utf-8")
    print(f"generate_database_doc: wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
